bin/pipeline-job: add pipeline summary

diff --git a/genomegenie/batch/templates/jobscript b/genomegenie/batch/templates/jobscript
--- a/genomegenie/batch/templates/jobscript
+++ b/genomegenie/batch/templates/jobscript
@@ -13,3 +13,11 @@ function sample_name() {
 
 # job command
 {{ job_cmd }}
+
+# NOTE: works only if exit codes are respected by the job command
+# Do not change, genomegenie.utils.job_status(..) relies on this
+if [[ $? == 0 ]]; then
+    echo Pipeline job finished: ${JOB_ID}
+else
+    echo Pipeline job failed: ${JOB_ID}
+fi
